version: '3'

services: 
  vulcano_api:
    build:
      dockerfile: src/Volcano.Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5001:5001"
      - "5000:5000"  