trigger: main

pool:
    vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'